// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewPost struct {
	Text string `json:"text"`
}

type NewVideo struct {
	Title  string `json:"title"`
	URL    string `json:"url"`
	UserID int    `json:"userId"`
}

type Post struct {
	Email string `json:"email"`
	Text  string `json:"text"`
	Name  string `json:"name"`
}

type User struct {
	ID   int    `json:"id"`
	Name string `json:"name"`
}

type Video struct {
	ID     int    `json:"id"`
	Tile   string `json:"tile"`
	URL    string `json:"url"`
	Author *User  `json:"author"`
}
